spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/savings_db
  
  data:
    redis:
      host: redis
  
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.superapp.product.savings: INFO




