server:
  port: 8083

spring:
  application:
    name: payment-rail-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000

# Payment Provider Configuration
payment:
  providers:
    stripe:
      enabled: true
      api-key: ${STRIPE_API_KEY:sk_test_dummy}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_dummy}
    paypal:
      enabled: false
      client-id: ${PAYPAL_CLIENT_ID:dummy}
      client-secret: ${PAYPAL_CLIENT_SECRET:dummy}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# Logging
logging:
  level:
    root: INFO
    com.superapp.core.payment: DEBUG




