server:
  port: 8082

spring:
  application:
    name: admin-identity-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_identity_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:superSecretKeyThatShouldBeChangedInProductionAndStoredSecurely123456789}
  expiration: 86400000  # 24 hours
  refresh-expiration: 604800000  # 7 days

# Security
security:
  allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:4000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# Logging
logging:
  level:
    root: INFO
    com.superapp.core.identity: DEBUG
    org.springframework.security: DEBUG




