spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/identity_db
    username: postgres
    password: postgres
  
  data:
    redis:
      host: redis
      port: 6379

# JWT Configuration (use environment variable in production)
jwt:
  secret: ${JWT_SECRET:dockerSecretKeyThatShouldBeChangedInProductionAndStoredSecurely123456789}

# Allow bean override for Docker
spring.main.allow-bean-definition-overriding: true




