server:
  port: 9001

spring:
  application:
    name: admin-bff

# Backend service URLs
services:
  identity: http://localhost:8081
  partner: http://localhost:8091
  catalog: http://localhost:8090
  risk: http://localhost:8083
  marketplace: http://localhost:8085/api/marketplace

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.superapp.bff.admin: DEBUG
    org.springframework.web: INFO
